### ISSUE TITLE
RPI zero?

### ISSUE THREAD

**Issue by jshep321** [HoerTech-gGmbH/openMHA#10]
Hi,
I have done some development on the PIZero(w) with the audioinjector zero (http://www.audioinjector.net/rpi-zero).  

Due to the size, it might be a better fit for some live testing.  Any idea if the single-core zero (w/ only 512MB RAM) could handle the load of this?  No time to play around with it now, but might be an interesting experiment, assuming the SW is not multi-threaded or has processing constraints.
Johnny

**Comment by tobiasherzke** [comment]
The load of openMHA depends on the configuration. YMMV.

**Comment by m-r-s** [comment]
We run it on the RPi model 3B and restrict the JACK and MHA process to one core [1].
It should work fine for the configuration we use in that project [2].

[1] https://github.com/m-r-s/hearingaid-prototype/
[2] https://github.com/m-r-s/hearingaid-prototype/blob/master/openMHA.cfg
