### ISSUE TITLE
mhacontrol unexpectedly resets jack connections

### ISSUE THREAD

**Issue by m-r-s** [HoerTech-gGmbH/openMHA#11]
Yesterday, during the preparation for the workshop, we found that the GUI (mhacontrol) in version v4.5.5 unexpectedly disconnects the JACK connections from and to the MHA when connecting to the MHA via network. This was on Windows using GNU/Octave 4.2.2. (or maybe 4.2.1).

We then tried openMHA version v4.5.4 which shows the expected behavior, leaving existing connections untouched.

**Comment by HoerTech** [comment]
Thank you for the report!

**Comment by hendrikkayser** [comment]
In the directory where mhacontrol is running there should be a file named "mhacfg_<host>_<port>_<name of instance>.mat"
Does the error still occur after you deleted this file?

**Comment by m-r-s** [comment]
We will test it again on 26th during the workshop.

**Comment by tobiasherzke** [comment]
Cause is a function of the connection dialogue to save the Jack connections that you make for all eternity. We will fix this by not saving the connections to a file in the next release.

**Comment by tobiasherzke** [comment]
This is fixed in release 4.5.6 by not calling the audio connection manager from mhacontrol.
