### ISSUE TITLE
Document "nop" state of MHA

### ISSUE THREAD

**Issue by bwilliges** [HoerTech-gGmbH/openMHA#12]
The "nop" state of MHA is missing in the Application manual, but listed as a possible keyword of "cmd"
`mha cmd?`

**Comment by tobiasherzke** [comment]
You mean in Figure 2?

"nop" and the other commands that can be assigned to cmd= are not the states themselves, but the state transitions. "nop" is the transition which does not change any state, which we use in MHA in the style of https://en.wikipedia.org/wiki/NOP

We could add small circular arrows to every state in Figure 2, labeled with "cmd=nop" and pointing back to the origin state. But my feeling is this would make the figure less readable. Any suggestions from you where we should document nop?

**Comment by tobiasherzke** [comment]
BTW, the current state of the MHA can be queried with "state?". "cmd?" will always give you "nop" as a result. Reason: When you save the configuration of the MHA to a file ("?save:filename"), and reread that file again into the mha, you usually do not want to assign to cmd the state transition that was last used on it. We made cmd essentially a write-only variable.

**Comment by bwilliges** [comment]
I would just add these two important pieces of information in written text to section 3.3 of the Application manual, something like:

The states of the openMHA host application are controlled by setting the write-only "cmd" variable. States can be queried by using "state?". [...] See Fig. 2 for an overview. After a state is executed, cmd will be set to "nop" to indicate that other states can now be set using cmd.

**Comment by tobiasherzke** [comment]
Thanks for the suggestion. Something like this will be in the next release.

**Comment by tobiasherzke** [comment]
This has been documented in release 4.5.6.
