### ISSUE TITLE
Throw error when in "stopped" status and attempting to change configuration

### ISSUE THREAD

**Issue by bwilliges** [HoerTech-gGmbH/openMHA#13]
Scenario: Processing one file, changing some settable host/plugin-variable, and then try to process the MHA again with "start" cmd.

Expected behaviour: Throw an error, because after the "stop" cmd mha is in a state, where its configuration cannot be changed (See Fig. 2, Application manual. You can write arguments, but it does not change things, until the mha was "released" and "prepared" once.

Actual behaviour: configuration arguments gets accepted without errors, but will not be evaluated. For the user it looks like there was no error in the processing chain, but the output will not be as expected. Very difficult to debug scenario here.

Example: Change outputfile-destination, after the mha has run once. This does not work, because the io.out-file is not correctly prepared. Working directory is mha/examples/01-dynamic-compression. "cmd?" are in there to "debug" the mha state.
`mha ?read:example_dc.cfg cmd=start cmd? cmd=stop io.out=1speaker_out.wav cmd? cmd=start cmd? cmd=stop cmd=quit`

adding release and prepare command and it works:
`mha ?read:example_dc.cfg cmd=start cmd? cmd=stop io.out=1speaker_out.wav cmd? cmd=release cmd=prepare cmd=start cmd=stop cmd=quit`

It would be nice, if it is needed to do the following (changing to "released" state before changing configurations):
`mha ?read:example_dc.cfg cmd=start cmd? cmd=stop cmd=release io.out=1speaker_out.wav cmd=prepare cmd=start cmd=stop cmd=quit`

**Comment by tobiasherzke** [comment]
Thanks for the report and the suggestion for a fix.

**Comment by tobiasherzke** [comment]
Since release 4.5.6, variables in MHAIOFile are locked between cmd=prepare and cmd=release, resulting in the expected error message.
