### ISSUE TITLE
java error, Running mhatest file on Matlab on Mac. 

### ISSUE THREAD

**Issue by SnandanSharma** [HoerTech-gGmbH/openMHA#14]
Hello 
I am not sure if this is the right platform to discuss problems about using MHA. If not then it will be great if someone can point me to either mailing list, forum for discussion. 

I am trying to start mha via Matlab. 
I am trying to run one of the mhatest file and I get the following error - 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Java exception occurred:
java.io.IOException: Cannot run program "mha": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 2 more

Error in shiftingTry (line 36)
  mha = mha_start;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Things that I have tried - 

- Make sure that javaaddpath adds the mhactl_java.jar file to the Matlab path.

- It seems that the mha.exe file cannot be located. So I tried adding it explicitly to Matlab path. I have already added javaaddpath to my Matlab path but get the error- which it seems it can not find the mha.exe.  Even if I do explicitly add mha.exe even then it can not locate it. 

- I can run mha with one of the example config files in Terminal. I can also run mha GUI by mhacontrol localhost in Matlab but only after starting mha in terminal. But if I try to start-up one of test file for examples. test_runexample01a.m I get the error shown above. 

Thanks a lot in advance !

**Comment by pmaanen** [comment]
Hi Snandan,

the openMHA matlab wrapper is controlled by some environment variables.
Try to add the following lines, adapted to your directory structure, to
your code:
setenv('MHA_INSTALL_DIR', "PATH-TO-YOUR/openMHA/bin" );
setenv('LD_LIBRARY_PATH', "PATH-TO-YOUR/openMHA/lib" );

Please report back if that helped.

**Comment by SnandanSharma** [comment]
Hi Paul 

Thanks for your answer. I tried and it helps. 

I have another question. 
I still can not start mha from Matlab and Is it even possible? I tried system('mha &') in Matlab to run mha.exe file but doesnt help. 
I can start mha via terminal but I am not sure how to start it via Matlab. Because if try to run one of the config files from Matlab I get the following error -


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

mha_query(mha,'','read:gain_live_double.cfg')
Error using mhactl_wrapper>mhactl_wrapper_2 (line 66)
An error occured while sending to MHA server:
[1: '?read:gain_live_double.cfg'] (mha_parser) not able to open file "gain_live_double.cfg" for reading.

Error in mhactl_wrapper (line 38)
  r = interface( handle, query );

Error in mha_query (line 17)
  s = mhactl_wrapper( handle, [base '?' query] );

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by pmaanen** [comment]
Hi Snandan,
sorry for the long silence!
Yes, it is possible to start mha from matlab: mha_start should start the mha executable and return a mha struct which can be used to control mha from matlab. The error message you are currently facing simply means that mha can not find the file you are instructing it or read. Make sure that your Matlab working directory is the same as the directory where the cfg is located. When using file to file processing you also have to make sure the audio files are in the same directory. Alternatively you could try using absolute pathes.

Hope that helps!
