### ISSUE TITLE
Installation - Make halts

### ISSUE THREAD

**Issue by Accostare** [HoerTech-gGmbH/openMHA#16]
On fresh win64 machine, followed 
Prerequisites, Preparation and compilation to and including writing make
Make exists at the point and with the message seen in attached image
Please send a direct message to me as soon as you can with what I should try next

![missingdll_missingljack](https://user-images.githubusercontent.com/45094596/48614557-3139b880-e997-11e8-8555-deffa59d8560.png)
)

**Comment by tobiasherzke** [comment]
The second point in "preparation" is "Copy libjack64.lib from the JACK installation to the lib directory in your Octave directory and rename it to libjack.a". With your octave setup, this should have created the file C:\Octave\Octave-4.4.1\lib\libjack.a, with the same contents as the original file C:\Program Files (x86)\Jack\lib\libjack64.lib. The linker error indicates that this file, C:\Octave\Octave-4.4.1\lib\libjack.a, was not found. Fix this and rerun make.
