### ISSUE TITLE
Bluetooth remote mic

### ISSUE THREAD

**Issue by GeraG** [HoerTech-gGmbH/openMHA#17]
Hello,

With newer hearing aids such as Oticon Opn supporting bluetooth connectivity, do you have any plans to work on an open source project to develop a do-it-yourself remote mic or interconnected table mic's for meetings similar to Phonak's Roger Mics or Oticon ConnectClip? This mic would stream audio to the bluetooth hearing aids.

This would greatly help with understanding speech in noise, in meetings, and understanding speech from distance lecturers.

Thanks!

**Comment by tobiasherzke** [comment]
Dear GeraG

we have no plans to add sound I/O adapters to specific bluetooth microphones into the MHA. If you can add these microphones as regular sound cards to your computer, you may be able to use them with the MHAIOPortaudio, MHAIOalsa, or MHAIOJack I/O adapters.
