### ISSUE TITLE
can't run mhacontrol command

### ISSUE THREAD

**Issue by shaghale** [HoerTech-gGmbH/openMHA#21]
Hi

I wanted to use this software but when i run mhacontrol command in matlab in windows 10, it gives a weird error. i checked MHA connection with mha test and it works fine. even the examples in mhatest folder works too. shall i add some other commands before mhacontrol? 
![errror](https://user-images.githubusercontent.com/30463803/51248804-2921d900-1946-11e9-9ee4-42547dff2fa5.PNG)

**Comment by pmaanen** [comment]
Hi shagale,
unfortunately we@HoerTech are currently busy with preparations for an event and can not help you until next week - sorry!

**Comment by tobiasherzke** [comment]
Dear shagale,

the error is "Connection refused". This can mean any of the following:

- MHA is not running
- MHA is listening on a different port or network interface than what you connect to with Matlab
- Your firewall is preventing the connection.

You can fix it by double-checking that your firewall allows connections from Matlab to MHA and by ensuring that Matlab and MHA agree on the network interface and port.
