### ISSUE TITLE
OpenMHA gui (pseudo)gain table for 3 channels

### ISSUE THREAD

**Issue by JohnAbarro** [HoerTech-gGmbH/openMHA#22]
Hey thanks for the previous issue about the bash script! 

Apparently, i'm using three channel inputs and two outputs. I'm struggling on setting the output to two only, since nchannels_out cannot be set. Well, I decided to leave one of the channels disconnected.

Now I'm having a dilemma with fitting the hearing aid from the gui. It only accepts two channels, which I would normally expect. What I can't figure out is how to modify the m files such that the first two channels are allotted for left and right and the third always set to zero gains? This is because the system uploads a gaintable of size  9 or 18, instead of size 27.

 Really appreciate your help, thank you :).

**Comment by pmaanen** [comment]
Hi John,
unfortunately we@HoerTech are currently busy with preparations for an event and can not help you until next week - sorry!

**Comment by hendrikkayser** [comment]
Hello John,
sorry for the late response!
Do I understand correctly that you don't want to modify the third channel or even don't use it at all?
I think your problem can be solved in the openMHA configuration file. If you upload your current version or give a MWE I'll have a look.

**Comment by hendrikkayser** [comment]
Hi John,
did you solve your problem?
If not, feel free to re-open this issue.
