### ISSUE TITLE
Sound energy estimation

### ISSUE THREAD

**Issue by Kyle2048** [HoerTech-gGmbH/openMHA#23]
Hi 

I am someone  interested in acoustic algorithm. When I tracked the OpenMHA source code for dc.cpp (dynamic compression), I saw the energy estimation as follows
![2019-02-19 11 33 34](https://user-images.githubusercontent.com/36362013/52988500-7c51e480-343a-11e9-9a0c-1392d208263f.png)
I can understand that in addition to DC bin and Nyquist bin, other bins need to be multiplied by 2. But according to Parseveal's theorem, I think DC bin and Nyquist bin should be multiplied by 1. Can you tell why you decided to multiply by 0.5 for energy estimation?

best regards

**Comment by tobiasherzke** [comment]
You are correct, the 0.5 factor is an error. This will be corrected in the next release.

**Comment by tobiasherzke** [comment]
This has been corrected in openMHA release 4.9.0.

The effect of the error should be negligible for typical configurations and signals. E.g. we had to adjust our expected output level in mha/mhatest/test_runexample01a.m by 0.06 dB to account for the correction.

**Comment by Kyle2048** [comment]
That's a good news for me.  Thanks for your answer.
