### ISSUE TITLE
No output from MHA (anymore) on Ubuntu 18.10

### ISSUE THREAD

**Issue by m-r-s** [HoerTech-gGmbH/openMHA#24]
I currently don't get any output from the MHA process on Ubuntu 18.10 on my Notebook, which I tested with various versions of openMHA from 4.6.0 to 4.8.1. The process runs but the output is zero.
Interestingly, [recordings with "wavrec" are empty](https://github.com/HoerTech-gGmbH/openMHA/issues/19#issuecomment-467857453
).

This morning, I saw the same behavior on a Notebook of a student with Ubuntu 18.10 who installed openMHA from the repository, which is why I report it here.
Currently I don't know what the reason could be and I will add any related information once I have a clue.

An example config which does not produce any output different from zero is the following:

**nchannels_in = 1
fragsize = 1024
srate = 48000
mhalib = iirfilter
mha.A = [1.0]
mha.B = [1.0]
iolib = MHAIOJack
cmd=start**

**Comment by pmaanen** [comment]
By default MHA does not autoconnect to any other IO port. Did you remember use jack_connect or a GUI to connect MHA other input/output devices? MHAIOJack can be instructed to autoconnect with the con_in and con_out configuration variables, e.g. 
`io.con_in=[system:capture_1]`
`io.con_out=[system:playback_1]`

**Comment by m-r-s** [comment]
Yes, I am sure. I prepared a little [testkit.zip](https://github.com/HoerTech-gGmbH/openMHA/files/2910628/testkit.zip)
It needs only openmha, jack_playrec and jackd (on top of a vanilla Ubuntu 18.10 USB live system), which I installed from the official Ubuntu repository and your Ubuntu 18.04 repository.
 
A sweep is fed into MHA with jack_playrec while its output is recorded.

![screenshot from 2019-02-27 14-12-15](https://user-images.githubusercontent.com/12151832/53496779-a3dc2900-3a9a-11e9-981d-80d19762edbf.png)

The resulting recording only contains zeros.

**Comment by pmaanen** [comment]
I just tried to reproduce the issue with your testkit on my developer machine, a bionic VM, and a cosmic VM. I could only reproduce the issue by not adding the Live session user to the audio group. On my machine and with Live session users permitted to do real-time scheduling the recording had the wrong length (28s vs 30s) but otherwise sounded fine.

**Comment by m-r-s** [comment]
You are right! Thank you, and sorry for wasting your time.

I forgot to add the user to the audio group after reinstalling Ubuntu.
Is this behavior is not expected when the user is not member of the audio group?
Maybe a warning could be issued by openMHA?
I also don't understand why it even fails with a dummy device...

will close the issue.

**Comment by pmaanen** [comment]
> Is this behavior is not expected when the user is not member of the audio group?
> I also don't understand why it even fails with a dummy device...

When jackd is first installed it displays a configuration ui where the user is asked if real time scheduling should be used. If this is answered "yes" it tries to do rt-related stuff even if later started without -R (use rt scheduling) or with -r (do not use rt scheduling) and regardless of audio driver. I got some error messages about failling memory allocations etc... This is only an empirical observation, I do not know where the postinstall script saves its output and where the output is used.

> Maybe a warning could be issued by openMHA?

I will investigate if this is possible

**Comment by suaefar** [comment]
Thank you. I think this would help first-time (and also some not so first-time) users :)
