### ISSUE TITLE
MHA GUI

### ISSUE THREAD

**Issue by KhaledAbdellatif** [HoerTech-gGmbH/openMHA#25]
Dear all, 

I am facing a Problem to open the MHA GUI. 
From the Manual it is written to the write the command "mhacontrol". 

first I had problemls with addin a Java path: 
 >> javaaddpath(C:\Program Files\openMHA\mfiles\mhactl_java.jar)

then it also didnt work so prom the Forum I tried the following commands: 

>> setenv('MHA_INSTALL_DIR', "PATH-TO-YOUR/openMHA/bin" );
>> setenv('LD_LIBRARY_PATH','C:\Pogram Files\openMHA\mfiles\libfuncs')

[image](https://user-images.githubusercontent.com/48767512/54704467-1476e280-4b3b-11e9-953d-3a8696e53931.png)

Thank you very much!!

**Comment by tobiasherzke** [comment]
> > > javaaddpath(C:\Program Files\openMHA\mfiles\mhactl_java.jar)

The string in the parenthesis needs to be enclosed in single quotes.

> [image]

mhacontrol does not start the mha, but connects to an instance that is already running. You have to start it before you can connect to it with mhacontrol.
