### ISSUE TITLE
MHA fitting GUI

### ISSUE THREAD

**Issue by KhaledAbdellatif** [HoerTech-gGmbH/openMHA#26]
Thanks Tobias for your quick response, 
What I would like to try is the GUI interface (eg client database dialog, audiogram editor).
Although I had the windows installer  installed, but I can not open the GUI.
Unfortunately, the documentation did not help me (which was mostly for developers)
Can you please help me with this?

**Comment by tobiasherzke** [comment]
We hope this is resolved by the getting-started guide that will be part of the next release and of which you received a pre-release version. If not, feel free to reopen this ssue.
