### ISSUE TITLE
index error when calling mhacontrol()

### ISSUE THREAD

**Issue by bengalensis** [HoerTech-gGmbH/openMHA#27]
Commands executed in Matlab R2018b: 
- `system(mha.exe &)`
- `mhacontrol.m` without input arguments

openMHA is running, after executing mhacontrol() index error appears (see screenshot)
![openMHA_index_error](https://user-images.githubusercontent.com/49186277/55387621-0b6e1400-5532-11e9-98e5-5e32e5835ec6.png)

**Comment by pmaanen** [comment]
Hi bengalensis,

I can not reproduce the error. A Quick Start Guide for Windows is in preparation, but it is not yet ready for public release. If you give me your email address ( my email can be found on [https://www.hoertech.de/de/hoertech/team.html](https://www.hoertech.de/de/hoertech/team.html )) I can send you a preliminary version in private.

Kind Regards,
Paul

**Comment by tobiasherzke** [comment]
I can also not reproduce the error. Please retry with the latest version of openMHA. If you still encounter errors, feel free to reopen this issue or create a new one.
