### ISSUE TITLE
A quick question about the mvdr filter

### ISSUE THREAD

**Issue by yuan9778** [HoerTech-gGmbH/openMHA#30]
This is more of a question than an issue. I tried your example 06-binaural-beamformer and noticed it used a mvdr filter. I was wondering how you guys generate the filter file. I read your documents and failed to find the answer. Could you provide some hints? Thanks much!

Regards,
Sanqing

**Comment by hendrikkayser** [comment]
Dear Sanqing,
the filter file was generated in Matlab using Matlab's freqz function with the head-related impulse responses (HRIR, http://medi.uni-oldenburg.de/hrir/) that are mentioned in the example configuration. The filter coefficients for the steering vectors were derived directly from the according HRIRs (measured with the hearing aid microphones). Regarding the noise covariance term in the MVDR solution a spatially diffuse noise field was assumed. This was realized by accumulating HRIRs from all azimuth angles available in the database for the horizontal plane (0° elevation) and computing the covariance matrix from the resulting transfer characteristics.
Currently we do not have such a Matlab script available in the openMHA tool set, but actually we plan to prepare one for one of the next releases.
I hope this helps you for the time being!

Best,
Hendrik

**Comment by yuan9778** [comment]
Hi Hendrik,

Thanks so much for your response. It is quite helpful and I'm looking
forward to your next github update.

I'm a programmer but new to the DSP area. Your openMHA project provides me
a great chance studing sound signal processing. When I proceed to
09-example (09-localizer-steering-beamformer
<https://github.com/HoerTech-gGmbH/openMHA/tree/master/examples/09-localizer-steering-beamformer>).
I have difficulties in understanding the following 2 steps:

1. For the class *doasvm_feature_extraction*, there is a member "max_lag"
(Maximum lag in samples between microphones), you initiate it with value 2
or 20. I guess 2 is for the pair of mics with the distance of 0.0149m. This
is correct for sampling rate of 48k but in this example it did a resampling
and the sampling rate was changed to 16k. Below is the calculation:
                           (0.0149 / 343) * 48000 = 2.085 samples.  For a
sampleing rate of 16000, it will be 0.695 sample.

2. For the class *doasvm_classification*, it needs the data from file
"matrices_4channel_front-rear_bte.cfg" to initiate its member w, b, x and
y. I read your paper " A discriminative learning approach to probabilistic
acoustic source localization" and got some ideas about how to generate
those data, but still not certain. Did you record sound from all 73
directions and use them as input files for doasvm_feature_extraction to
generate training data?  Which liblinear command you used for training?
Where did you get the data for x and y? Maybe I understand it all wrong. It
will be great help if you can shed some light on this.

Since you will provide the Matlab script for mvdr filter in the next github
update, is it possible that you can send me a copy in advance if you
already have it in hand?

Thanks again for your time and the openMHA project from which I learn a lot.

Regards,
Sanqing
