### ISSUE TITLE
problems with mhacontrol

### ISSUE THREAD

**Issue by Flobon** [HoerTech-gGmbH/openMHA#32]
Hi, 
first of all, I use mha the first time. Therefore, my problems may be rather simple.

I started mhacontrol with octave and the gui opens as expaxcted, but, however, the 'levels' button is missing. Furthermore, the fitting cannot be done properly. After selecting an audiogram and clicking ok, an error occurs "no fittable plugins available", and you are back in the mhacontrol-gui. Did I forget anything during the installation step?

**Comment by hendrikkayser** [comment]
Hello,
it seems that you don't have a proper openMHA configuration running.
Please check out the instructions provided here:
http://www.openmha.org/docs/openMHA_starting_guide.pdf

In particular, Example 5 should be helpful.

Best,
Hendrik
