### ISSUE TITLE
Cannot download source code.zip

### ISSUE THREAD

**Issue by dhanashri-innovision** [HoerTech-gGmbH/openMHA#33]
Hi,
I am very new to openMHA. So to start with, I tried to download the source code.zip and source code.tar files to have the glimpses of the programming from the link,
https://github.com/HoerTech-gGmbH/openMHA/releases

But everytime I downloaded the file, it downloads the installer.exe files and not the C files.
If somebody has any other way to download the same please let me know.

**Comment by hendrikkayser** [comment]
Hello,
I just checked the downlod links on the release page: 
https://github.com/HoerTech-gGmbH/openMHA/archive/v4.10.0.zip
https://github.com/HoerTech-gGmbH/openMHA/archive/v4.10.0.tar.gz
... and they worked fine for me. Please try again.

Best,
Hendrik

**Comment by dhanashri-innovision** [comment]
Hello,
I just wanted the cpp or matlab files for the examples included. e.g.
00-gain etc

Regards,
Dhanashri Vashta.
9029575757
