### ISSUE TITLE
Plugin development pipeline

### ISSUE THREAD

**Issue by sbashford** [HoerTech-gGmbH/openMHA#35]
Hello!

What a fascinating project!

Do you have any recommendations on creating a pipeline for developing a plugin? How might one consume this project for plugin development?

I believe a plugin developer needs to include [mha_plugin.hh](https://github.com/HoerTech-gGmbH/openMHA/blob/master/mha/libmha/src/mha_plugin.hh) and link to libopenmha.*, correct?

Am I correct that neither the pre-compiled binary package nor the [install target](https://github.com/HoerTech-gGmbH/openMHA/blob/df1a3d5b42c858cdfb7f497ca9975beb9b2bcb31/Makefile#L61) exposes mha_plugin.hh? If so, would you recommend that a plugin developer explicitly includes ${openmha_root}/mha/libmha/src in their build-system?

Thanks for your help.

**Comment by tobiasherzke** [comment]
Thanks for the question, I have copied it to the openMHA forum, let's discuss it there: https://forum.openmha.org/viewtopic.php?f=18&p=83

I'm closing this issue here because the topic is not a software error.
