### ISSUE TITLE
mhacontrol issue

### ISSUE THREAD

**Issue by dhanashri-innovision** [HoerTech-gGmbH/openMHA#36]
I tried running OpenMHA project with open mha running on command prompt.
whenever I give mhacontrol command with no argument, the photo for OpenMHA pops up, and then it gives the error "Index in position 1 exceeds in array bound" in a new pop up window.
if I press OK, 
I get this message in command window.

>> mhacontrol
Warning: Index in position 1 exceeds array bounds.
C:\Program Files\openMHA\mfiles\mha_findid.m:35
C:\Program Files\openMHA\mfiles\mha_get_basic_cfg_network.m:24
C:\Program Files\openMHA\mfiles\mhacontrol.m:52 
> In mhacontrol (line 81) 
Index in position 1 exceeds array bounds.

Error in mha_findid (line 35)
      cfg.(csBase{idx(1),2}) = csBase{idx(1),1};

Error in mha_get_basic_cfg_network (line 24)
  [s.base,s.all_id_plugs] = mha_findid(mha);

Error in mhacontrol (line 52)
    s = mha_get_basic_cfg_network( mha );

**Comment by tobiasherzke** [comment]
Let's help you in the openMHA forum, I have copied your question there: https://forum.openmha.org/viewtopic.php?f=18&t=84

Closing it here since it can probably be solved with usage instructions. Please give more details about what you have done over at the forum.
