### ISSUE TITLE
fftw-2.1.5 directory listed inside .gitignore but already present in the repository

### ISSUE THREAD

**Issue by mroavi** [HoerTech-gGmbH/openMHA#37]
I noticed that the 'fftw-2.1.5' directory was added to the '.gitignore' file inside the 'external_libs' folder after it had already been added and committed to the repo. If the folder is not meant to be tracked, why not remove it from the repo? I find it quite annoying that the 'confgure' file inside this folder changes after building the project and hence appears as 'modified' in my working directory.

**Comment by tobiasherzke** [comment]
The fftw directory is in .gitignore to ignore the autotools build artifacts created during build. A workaround for not having the fftw configure skript modified by mere building is to uninstall autoconf from your build environment.
