### ISSUE TITLE
mhacontrol resets calibration

### ISSUE THREAD

**Issue by m-r-s** [HoerTech-gGmbH/openMHA#4]
When connecting to openMHA with the Octave-based GUI (mhacontrol.m) the calibration provided in the configuration file is overwritten with default values.
This is unexpected behavior.

As a result openMHA can only be calibrated xor fitted but not calibrated and fitted.

**Comment by suaefar** [comment]
I implemented a temporary "fix" #5

**Comment by tobiasherzke** [comment]
I confirm the observed behaviour. 

The reason why it behaves like this, is separation of configuration and calibration, see below. But as you are now the second openMHA user running into this problem, I think we should address this issue sooner than planned, i.e. before we release a generic calibration tool.

Ultimately, calibration is done using the configuration variables (of plugin transducers). But suppose you have multiple identical setups, performing the same signal processing, and which are connected to identical sound hardware. The production spread of the sound hardware will require different calibration values for each instance.

The idea to solve this is to have a calibration tool inside mhacontrol which can walk the user through the necessary measurement steps to calibrate their system, and then save the calibration data on the system where mhacontrol is executing.

The next time mhacontrol starts connected to the same system, it would reupload the latest calibration data.

The calibration tool that we have right now is not generic enough to calibrate arbitrary sound hardware. This will be addressed by the calibration tool to be developed next year.

Our fix for now should be to not modify the values in the transducers plugin if we have never stored calibration values for that system.

**Comment by suaefar** [comment]
That sounds like an intuitive solution to me.

**Comment by hendrikkayser** [comment]
Was fixed by release 4.5.4.

**Comment by hendrikkayser** [comment]
There was a glitch in yesterday's release 4.5.4. This issue will be fixed very soon.

**Comment by hendrikkayser** [comment]
Done.
