### ISSUE TITLE
(mhafw_lib) IO error: (mhajack) Unable to connect to JACK server 'default' as client 'MHA'

### ISSUE THREAD

**Issue by chozillla** [HoerTech-gGmbH/openMHA#40]
I had this issue when I tried to run gain_live_getting_started.cfg. I deleted jack2 and redownladed it.
Another separate issue that prompted me to delete jack2 in the first place is how do you set the buffer size in Jack? Jack had it set at 512 and openMHA wanted 64.

**Comment by hendrikkayser** [comment]
You don't have the jack server runnig, so openMHA can not connect to it. You'll find some hints how to set up and start it in our [starting guide](http://www.openmha.org/docs/openMHA_starting_guide.pdf). Please use our forum under https://forum.openmha.org/  for usage-related questions. The example from the starting guide can be discussed [here](https://forum.openmha.org/viewtopic.php?f=11&t=7&sid=86dd85c343465673248f21b85e130de1).
