### ISSUE TITLE
Install Location MacOS

### ISSUE THREAD

**Issue by chozillla** [HoerTech-gGmbH/openMHA#41]
Hello,

I went through the installation process and installed this version from 4.11. Where is openMHA installed on my computer? I can't seem to locate 4.12. 

Thank you

**Comment by pmaanen** [comment]
Hi Chemay, 

the installer installs openMHA at different locations within `/usr/local`:
Executables go into `/usr/local/bin`
Libraries go into `/usr/local/lib/openmha`
Matlab tools into `/usr/local/lib/openmha/mfiles`
Examples and misc files `/usr/local/lib/share/openmha`
Manuals are found in `/usr/local/lib/doc/openmha`

Hope this helps! Please use our [forum](https://forum.openmha.org) in the future where question may be seen by more users.

Kind Regards,
Paul

**Comment by chozillla** [comment]
Hello Paul,

I still was not able to locate those files in those directories after installing the update via the .pkg file.However, I was able to install version 4.12 from the zip file.

-Chemay
