### ISSUE TITLE
Compiling failure for `aarch64` (ARMv8 64 bit ARM architecture)

### ISSUE THREAD

**Issue by chriskeeser** [HoerTech-gGmbH/openMHA#44]
Compiling the latest version from source on a machine with `uname -m` = `aarch64` fails due to what appears to be a few flags not being set / not being set correctly. 

* Specifically, the `gtfb_simd` module (which should only be compiled for x86) is being built (and failing).
* I also wonder if other ARM specific optimizations and choices are not being set up correctly (like using NEON)

**Comment by chriskeeser** [comment]
Fully owning this is a very hacky way to get it to compile (and may not even be fully valid), but here is what I did to make it work.  I'm sharing in this hopes that this might save effort for the maintainer and accelerate getting this change put in.

```
$ git diff configure
diff --git a/configure b/configure
index 5ac7c1f..6324259 100755
--- a/configure
+++ b/configure
@@ -85,8 +85,8 @@ chklib(){
     fi

     case $ARCH in
-        armhf)
-            echo "COMPILERPREFIX=arm-linux-gnueabihf-"
+        aarch64)
+            echo "COMPILERPREFIX=aarch64-linux-gnu-"
             ;;
         arm*)
             ;;
@@ -192,11 +192,11 @@ chklib(){
     esac

     case $ARCH in
-        armhf)
-            echo "COMPILERPREFIX=arm-linux-gnueabihf-"
+        aarch64)
+            echo "COMPILERPREFIX=aarch64-linux-gnu-"
             ;;
-        arm*)
-            echo "SSE+=-mcpu=cortex-a8 -mfloat-abi=hard -mfpu=neon"
+        aarch*)
+            echo "SSE+=-mcpu=cortex-a73 -mfloat-abi=hard -mfpu=neon"
             ;;
         x86_64*|i686*)
             echo "SSE+=-msse -msse2 -mfpmath=sse"
             
             
$ git diff mha/plugins/plugin.mk
diff --git a/mha/plugins/plugin.mk b/mha/plugins/plugin.mk
index efb3958..e28e65a 100644
--- a/mha/plugins/plugin.mk
+++ b/mha/plugins/plugin.mk
@@ -32,7 +32,7 @@ endif
 endif

 ifeq "$(EXCLUDE_FROM_ARM_COMPILATION)" "yes"
-ifeq "$(findstring arm, $(ARCH))" "arm"
+ifeq "$(findstring aarch64, $(ARCH))" "aarch64"
 # this plugin cannot be compiled for ARM processors.
 dummy02:
        @echo "not compiling" $(PLUGINS) "since it cannot be compiled for ARM"
```

**Comment by tobiasherzke** [comment]
Hi Chris,

you have solved your problem. I confirm that your hack should enable compilation on 64 bit ARM linux.

Out of curiosity:
Are you cross-compiling or compiling natively on aarch64?
Which board and OS are you targetting? Sound card?

I am closing this issue since you have solved it, but you can still reply. As you have noticed, aarch64 is currently not on our list of target architectures, but there should be nothing major that would prevent you from compiling for that arch or any other linux target architecture. We may add aarch64 to our target architectures when we see sufficient need or benefit. What led you to choose aarch64?

**Comment by chriskeeser** [comment]
Hi tobiasherzke,

* I am currently compiling natively on aarch64
* We are targeting the:
  * Khadas VIM3 (Pro), Amlogic A311D SoC
  * Linux OS (4.9 kernel, debian / ubuntu distro)
  * Our own custom sound card that interfaces with the TDM peripheral of the Amlogic device.

`aarch64` is the name given to `ARMv8` devices (like the cortex-a73 and cortex-a53).  We are targeting this hardware because of the significant increase in processing capability provided by ARMv8 devices.

**Comment by tobiasherzke** [comment]
Hi Chris,

thanks for the info! We have the VIM3 on our radar, but I was not aware that it supports TDM. Interesting! Maybe we can adapt our sound card https://github.com/HoerTech-gGmbH/Cape4all to work with this board! What do you think?

- For the Linux image, I assume you are following https://github.com/khadas/fenix/blob/master/README.md ?
- Why the old kernel? Some drivers for the board not yet in mainline?

**Comment by chriskeeser** [comment]
Hi tobiasherzke,

> thanks for the info! We have the VIM3 on our radar, but I was not aware that it supports TDM. Interesting! Maybe we can adapt our sound card https://github.com/HoerTech-gGmbH/Cape4all to work with this board! What do you think?

It think it might be a good idea! The TDM peripheral on the Amlogic A311D is very powerful (we are utilizing 16 slots @ 48 Ksps @ 32 bits / slot) although it is a bit quirky ;)

* Yes, we utilize the fenix build to generate the VIM3 image (then do extra installations / compilations on device)
* Cruft and difficulty migrating away from it at the moment.  Our plan is to try and migrate to a more recent kernel before too long.

**Comment by tobiasherzke** [comment]
Thanks for the info. Investigating options for aarch64, I think you should omit  `-mfloat-abi=hard -mfpu=neon`. In the best case, they have not effect, in the worst case, they will cause errors. Enabling hardware floating point and vectorization is already implied by -O3 when compiling for aarch64 with gcc, and the -mfloat-abi and -mfpu options are not mentioned in https://gcc.gnu.org/onlinedocs/gcc-9.3.0/gcc/AArch64-Options.html. You may want to consider replacing your `-mcpu` option with `-mcpu=cortex-a73.cortex-a53` in order to optimize for the VIM3 CPU.

**Comment by chriskeeser** [comment]
Thanks tobiasherzke. 

I'm making these tweaks to the autotools configure scripts and I was wondering if the second time that the `COMPILERPREFIX` is specified on line 196 necessary?  I'm a bit new to the autotools way, and it seems like the `COMPILERPREFIX` is already set on line 89.

Also, if I make these changes and open a Pull Request, would that be helpful to you?

**Comment by tobiasherzke** [comment]
Hi Chris,

we are not using autotools for openMHA, we only use a similarly named shell script.

COMPILERPREFIX is our workaround for cross-compilation. For compiling natively, it is not needed.

There is no need to create a pull request. I have already placed a diff to compile for aarch64 into our team's code-review queue.

It will probably take some time to decide if we want to add support for aarch64, and then to land this change onto git branch development, because we will need to extend our CI pipeline to cover aarch64, and add aarch64 support to dependencies.

In the meantime, this is the diff that I have proposed internally (based on branch development):
```
diff --git a/configure b/configure
index f12cd56..a51ed7f 100755
--- a/configure
+++ b/configure
@@ -202,6 +202,9 @@ gccver(){
         arm*)
             echo "SSE+=-mcpu=cortex-a8 -mfloat-abi=hard -mfpu=neon"
             ;;
+        aarch64)
+            echo "SSE+=-mcpu=cortex-a73.cortex-a53"
+            ;;
         x86_64*|i686*)
             echo "SSE+=-msse -msse2 -mfpmath=sse"
             ;;
diff --git a/mha/plugins/plugin.mk b/mha/plugins/plugin.mk
index fc28156..06ab28c 100644
--- a/mha/plugins/plugin.mk
+++ b/mha/plugins/plugin.mk
@@ -37,6 +37,11 @@ ifeq "$(findstring arm, $(ARCH))" "arm"
 dummy02:
 	@echo "not compiling" $(PLUGINS) "since it cannot be compiled for ARM"
 endif
+ifeq "$(findstring aarch64, $(ARCH))" "aarch64"
+# this plugin cannot be compiled for ARM processors.
+dummy02:
+	@echo "not compiling" $(PLUGINS) "since it cannot be compiled for ARM"
+endif
 endif
 
 ifeq "$(NEEDS_BOOST)" "yes"
diff --git a/mha/tools/mfiles/mha_start.m b/mha/tools/mfiles/mha_start.m
index fdbe9fb..a2ce46b 100644
--- a/mha/tools/mfiles/mha_start.m
+++ b/mha/tools/mfiles/mha_start.m
@@ -103,7 +103,7 @@ function [mha_handle, mha_process] = mha_start( port, pre_binary, post_binary )
     PATH_backup = getenv('PATH');
     remove_octave_directories_from_windows_path()
   end
-  
+
   octave_version = ver('Octave');
   % octave 4.0.0 did not translate cellstrings correctly to Java string arrays.
   if( isoctave() && strcmp(octave_version.Version,'4.0.0') )
@@ -113,10 +113,11 @@ function [mha_handle, mha_process] = mha_start( port, pre_binary, post_binary )
     try
       mha_process = javaruntime.exec(command);
     catch exception
-      if strcmp(exception.message, ...
-                ['[java] java.lang.OutOfMemoryError: unable to create ', ...
-                 'native thread: possibly out of memory or ', ...
-                 'process/resource limits reached'])
+      exception.message
+      strcmp(exception.message, ...
+                '[java] java.lang.OutOfMemoryError: unable to create ')
+      if ~isempty(strcmp(exception.message, ...
+                '[java] java.lang.OutOfMemoryError: unable to create '))
         disp(['expected exception for this octave version, ', ...
               'does not affect functionality'])
       else
@@ -126,12 +127,12 @@ function [mha_handle, mha_process] = mha_start( port, pre_binary, post_binary )
   else
     mha_process = javaruntime.exec(command);
   end
-  
+
   % restore PATH
   if ispc() && isoctave()
     setenv('PATH', PATH_backup);
   end
-  
+
   connection = acceptor.accept();
   reader = javaObject('java.io.BufferedReader', ... 
                       javaObject('java.io.InputStreamReader', ...
@@ -143,7 +144,7 @@ function [mha_handle, mha_process] = mha_start( port, pre_binary, post_binary )
   reader.close();
   connection.close();
   acceptor.close();
-  
+
 % Local Variables:
 % mode: octave
 % indent-tabs-mode: nil
```

**Comment by tobiasherzke** [comment]
BTW, are you compiling for bionic, focal, or buster?

**Comment by chriskeeser** [comment]
Thank you for sharing the diff, I will incorporate the relevant changes shown.

I am compiling for Ubuntu Bionic (18.04 LTS)

**Comment by tobiasherzke** [comment]
With today's release, 64 bit ARM linux became one of our target platforms. No need to apply patches anymore.
