### ISSUE TITLE
osc2ac documentation invalid

### ISSUE THREAD

**Issue by gisogrimm** [HoerTech-gGmbH/openMHA#47]
documentation (and previous versions) of osc2ac allow specification of an ac variable name by writing

vars = [acname:/oscpath]

According to the documentation this will create the MHA AC variable "acname" for the OSC path "/oscpath". However, a variable "acname:/oscpath" is created.

**Comment by tobiasherzke** [comment]
This has been fixed in commit 9f37b91 which is available now in branch development and will be part of the upcoming 4.14.0 release.

**Comment by gisogrimm** [comment]
Thank you!
