### ISSUE TITLE
Compile and install

### ISSUE THREAD

**Issue by jamshidiant** [HoerTech-gGmbH/openMHA#50]
Hi,
when I run the "./configure && make install" code in mingw64 I got this message.
I use windows 10, 64-bit

$ ./configure && make install
PLATFORM=MinGW
DYNAMIC_LIB_EXT=.dll
ARCH=x86_64
PREFIX=/home/Admin/openMHA
./configure: line 132: pkg-config: command not found
WITH_JACK=yes
WITH_EIGEN=yes
CXXSTANDARD=c++17
GCC_VER=-10
BUILD_DIR=x86_64-MinGW-gcc-10
CXXFLAGS+=-Wmisleading-indentation  -Wlogical-op -Wduplicated-cond -Wduplicated-branches  -Wformat-signedness
CFLAGS+=-Wmisleading-indentation  -Wlogical-op -Wduplicated-cond -Wduplicated-branches
SSE+=-msse -msse2 -mfpmath=sse
OPTIM=-O3 $(SSE) -ffast-math -fomit-frame-pointer -fno-finite-math-only
CXXFLAGS+=-Wall -Wextra -Wnon-virtual-dtor -Wformat -Werror -std=$(CXXSTANDARD) -fPIC $(OPTIM) -g
CFLAGS+=-Wall -Wextra -Werror -std=gnu11 -fPIC $(OPTIM) -g
make -C external_libs
make[1]: Entering directory '/home/Admin/openMHA/external_libs'
git clone https://github.com/chriskohlhoff/asio network-asio
fatal: destination path 'network-asio' already exists and is not an empty directory.
make[1]: *** [Makefile:123: network-asio/.gitignore] Error 128
make[1]: Leaving directory '/home/Admin/openMHA/external_libs'
make: *** [Makefile:52: external_libs] Error 2

what should I do?

**Comment by tobiasherzke** [comment]
> git clone https://github.com/chriskohlhoff/asio network-asio
> fatal: destination path 'network-asio' already exists and is not an empty directory.

Your openMHA directory contains leftovers from a previous compilation attempt.

> what should I do?

Delete everything that is not in openMHA git before retrying: `git clean -ffdx .`

**Comment by jamshidiant** [comment]
Should I navigate to a directory and then type the command "git clean -ffdx"?

**Comment by jamshidiant** [comment]
Thank you for your reply. You are right, my network connection was lost during the previous compilation. I remove it and it was fixed.
