### ISSUE TITLE
how to run commands after compiling

### ISSUE THREAD

**Issue by jamshidiant** [HoerTech-gGmbH/openMHA#51]
I installed the openMHA package but I want to check the variables and now I compiled the openMHA. After that, I can run the mha.exe from "./bin/" directory and got this message.

`
#############################################################
# ATTENTION: THIS BUILD OF OPENMHA IS NOT A RELEASE VERSION #
#############################################################

The Open Master Hearing Aid (openMHA) server version 4.16.0+
Copyright (c) 2005-2021 HoerTech gGmbH, D-26129 Oldenburg, Germany

This program comes with ABSOLUTELY NO WARRANTY; for details see file COPYING.
This is free software, and you are welcome to redistribute it
under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE, Version 3;
for details see file COPYING.
'
but there is no place to run the commands or navigating to directories to run the examples. Did I miss anything?

On the other hand, how can I run the compiled version of openMHA from 'cmd'? I add the path to the environment variables. after running the 'mha --interactive'  in cmd, I got the following pop-up messages

mha.exe - system error
The code execution cannot proceed because libsndfile-1.dll was not found. Reinstalling the program may fix this problem.

mha.exe - system error
The code execution cannot proceed because libgcc_s_seh-1.dll was not found. Reinstalling the program may fix this problem.

**Comment by tobiasherzke** [comment]
Dear user, we use these github issues for tracking errors in the software.

For questions about openMHA, please use the openMHA forum at https://forum.openmha.org/, thank you!

Please also refer to the existing documentation at http://www.openmha.org/. We have a getting-started guide there.

**Comment by jamshidiant** [comment]
Thank you for your reply. I send the message in the forum.
I thought maybe my problem is an issue. I compile and install openMHA 2 months ago on another system, but I can't send commands in the new system.
