### ISSUE TITLE
 Native compilation Matlab Coder Example 23 Error

### ISSUE THREAD

**Issue by steffendasenbrock** [HoerTech-gGmbH/openMHA#52]
Hi :) 

I've tried to replicate the Matlab Coder Example 23 on the native compilation method. Generating the C-Code using make.m worked fine. I did not do any changes to process.m. After copying the content of codegen/lib/process/ to my own folder "mha/plugins/steffensplugin" as well as the content of plugin_skeleton (+renaming the file matlabcoder_skeleton.cpp to steffensplugins.cpp) I tried "make install" and got the following:

[...]
make[2]: Leaving directory '/home/steffen/Documents/openMHA/mha/plugins/adaptive_feedback_canceller'
make -C steffensplugin
make[2]: Entering directory '/home/steffen/Documents/openMHA/mha/plugins/steffensplugin'
g++ -Wmisleading-indentation  -Wlogical-op -Wduplicated-cond -Wduplicated-branches  -Wformat-signedness -Wall -Wextra -Wnon-virtual-dtor -Wformat -Werror -std=c++17 -fPIC -O3 -msse -msse2 -mfpmath=sse -ffast-math -fomit-frame-pointer -fno-finite-math-only -g -isystem /home/steffen/Documents/openMHA/external_libs/x86_64-linux-gcc-9/include -I../../libmha/src -c -o x86_64-linux-gcc-9/steffensplugin.o steffensplugin.cpp
In file included from steffensplugin.cpp:21:
steffensplugin.cpp: In function ‘int MHA_DYNAMIC_MHAInit(algo_comm_t, const char*, void**)’:
../../libmha/src/mha_plugin.hh:559:60: error: no matching function for call to ‘matlabcoder_skeleton_t::matlabcoder_skeleton_t(algo_comm_t&, const char*&)’
  559 |                 *handle = new classname(algo_comm,algo_name);          \
      |                                                            ^
../../libmha/src/mha_plugin.hh:655:5: note: in expansion of macro ‘MHAPLUGIN_INIT_CALLBACKS_PREFIX’
  655 |     MHAPLUGIN_INIT_CALLBACKS_PREFIX(prefix,classname)           \
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../libmha/src/mha_plugin.hh:754:3: note: in expansion of macro ‘MHAPLUGIN_CALLBACKS_PREFIX’
  754 |   MHAPLUGIN_CALLBACKS_PREFIX(MHA_DYNAMIC_,classname,indom,outdom)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
steffensplugin.cpp:117:1: note: in expansion of macro ‘MHAPLUGIN_CALLBACKS’
  117 | MHAPLUGIN_CALLBACKS(matlabcoder_skeleton, matlabcoder_skeleton_t, wave, wave)
      | ^~~~~~~~~~~~~~~~~~~
steffensplugin.cpp:40:3: note: candidate: ‘matlabcoder_skeleton_t::matlabcoder_skeleton_t(algo_comm_t&, const string&, const string&)’
   40 |   matlabcoder_skeleton_t(algo_comm_t & ac,
      |   ^~~~~~~~~~~~~~~~~~~~~~
steffensplugin.cpp:40:3: note:   candidate expects 3 arguments, 2 provided
make[2]: *** [../../../rules.mk:45: x86_64-linux-gcc-9/steffensplugin.o] Error 1
make[2]: Leaving directory '/home/steffen/Documents/openMHA/mha/plugins/steffensplugin'
make[1]: *** [../../rules.mk:105: steffensplugin] Error 2
make[1]: Leaving directory '/home/steffen/Documents/openMHA/mha/plugins'
make: *** [Makefile:49: mha/plugins] Error 2

What am I missing? The error says that I'm trying to call a function which is not there, right? But was I supposed to make changes to the code in this example? 

In the Manual it says:

_The user then has to manually add MHAParser::* configuration variables and translate them
to appropriate types and pass them to the generated code when calling the signal processing
functions_

Since the function (channel switch) does not involve any configuration variables I do not need to add this right?

Best regards,

Steffen

**Comment by tobiasherzke** [comment]
> In the Manual it says:
> 
> _The user then has to manually add MHAParser::* configuration variables and translate them to appropriate types and pass them to the generated code when calling the signal processing functions_
> 
> Since the function (channel switch) does not involve any configuration variables I do not need to add this right?

What happens when you add this? Does it fix the compilation?

**Comment by steffendasenbrock** [comment]
I think I do not fully understand what MHAParser configuration variables do add. What would be an example?
I changed the constructor of matlabcoder_skeleton_t

from three inputs:
matlabcoder_skeleton_t(algo_comm_t & ac, const std::string&, const std::string&)
to two inputs:
matlabcoder_skeleton_t(algo_comm_t & ac, const std::string&)

Yet, I don't not fully understand why this even worked.

**Comment by tobiasherzke** [comment]
Thank you for the fix! We should include it in the next release. I will send you a code review request.

As a workaround, users who run into this error should delete line 41 of file examples/23-matlab-coder/plugin_skeleton/matlabcoder_skeleton.cpp before copying and renaming it.
