### ISSUE TITLE
Unable to install openmha on ubuntu 20.04

### ISSUE THREAD

**Issue by jellison102219** [HoerTech-gGmbH/openMHA#53]
This may not be an issue but when following the installation instructions for Linux Ubuntu (see https://github.com/HoerTech-gGmbH/openMHA/blob/master/INSTALLATION.md) 
Here is the sequence: 

`ubuntu@ubuntu:~/Desktop$ wget -qO- http://apt.hoertech.de/openmha-packaging.pub | sudo apt-key add -
OK
ubuntu@ubuntu:~/Desktop$ sudo apt-add-repository 'deb [arch=amd64] http://apt.hoertech.de focal universe'
Hit:1 http://apt.hoertech.de bionic InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:4 http://apt.hoertech.de focal InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Hit:6 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Reading package lists... Done
ubuntu@ubuntu:~/Desktop$ sudo apt install openmha openmha-examples
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package openmha is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'openmha' has no installation candidate
ubuntu@ubuntu:~/Desktop$ 
`
Am I missing a step? 

Thanks in advance. 

JE

**Comment by tobiasherzke** [comment]
I cannot reproduce your error. You seem to have upgraded from Ubuntu 18.04 to Ubuntu 20.04 recently, at least, your output shows both of these lines:
```
Hit:1 http://apt.hoertech.de/ bionic InRelease
Hit:4 http://apt.hoertech.de/ focal InRelease
```
Maybe your packaging system is in some erroneous state. I would try this in your situation:
```
sudo apt-add-repository --remove 'deb [arch=amd64] http://apt.hoertech.de focal universe'
sudo apt-add-repository --remove 'deb [arch=amd64] http://apt.hoertech.de bionic universe'
sudo nano /etc/apt/sources.list # Edit to make sure that no "apt.hoertech.de" entries remain
sudo apt update
sudo apt purge libopenmha liblsl openmha openmha-examples
sudo apt-add-repository 'deb [arch=amd64] http://apt.hoertech.de focal universe'
sudo apt install openmha openmha-examples
```
