### ISSUE TITLE
Github Organisation Website link should be: https://www.hz-ol.de

### ISSUE THREAD

**Issue by digitalfrost** [HoerTech-gGmbH/openMHA#57]
Github Organisation Website link should be: https://www.hz-ol.de

not http://www.hoertech.de/ :
![Screenshot (16)](https://user-images.githubusercontent.com/286763/185786066-1cc7c5b2-b0c0-4344-bc42-2703dc6214da.png)

**Comment by tobiasherzke** [comment]
Yes, we are aware that many files in openMHA still mention HörTech while the non-profit company is now named Hörzentrum Oldenburg. Also, others, and publications, link to the https://github.com/HoerTech-gGmbH/something, therefore we cannot really change the GitHub organization name without breaking existing stuff out there.

Regarding this link, I'm not too concerned as long as it forwards to the correct URL. But we'll discuss internally if it makes sense to update just this link, or maybe also the display name, the description and the logo.
