### ISSUE TITLE
Unable to set --compSpeed=2 option while using nalnl2wrapper (using wine).

### ISSUE THREAD

**Issue by dhruvvyas90** [HoerTech-gGmbH/openMHA#61]
While using `nalnl2wrapper.exe` using wine, I am unable to set `--compSpeed=2` (for dual mode). It throws the following error.

what():  Invalid compSpeed: Expected: 0, 1, or 2. Got: 2

After a little bit of digging, it seems `parser.cpp` needs to check for all 3 options (0, 1 & 2) rather than just 2 (0 & 1). 

Example command to replicate the issue.

`wine64 ../nalnl2wrapper/nalnl2wrapper.exe --ac=50,50,50,50,50,50,50,50,50 --bc=50,50,50,50,50,50,50,50,50 --ac_other=50,50,50,50,50,50,50,50,50 --level=55,65,75 --date_of_birth=19580101 --tonal=0 --experience=0 --adultChild=0 --gender=1 --compSpeed=2 --bilateral=0 --mic=1 --direction=0 --limiting=1 --channels=18 --wbct=52 --bandwidth=1 --hatype=3 --tubing=2 --venting=0 --userecd=0`

**Comment by tobiasherzke** [comment]
Confirmed. Thanks for the report!

**Comment by tobiasherzke** [comment]
Fixed in branch development. Fixed installers are available at the locations referenced in https://github.com/HoerTech-gGmbH/openMHA/blob/development/README_NALNL2.md.

Branch development will be merged into master during the next openMHA release, which is planned for the end of 2023.
