### ISSUE TITLE
how to train 34-DNN-based-speech-enhancement/model_bmfwf.pt ?

### ISSUE THREAD

**Issue by zuowanbushiwo** [HoerTech-gGmbH/openMHA#66]
Dear Sir
Are there training scripts and guidelines for training the model_bmfwf.pt model ？
thanks！

**Comment by hendrikkayser** [comment]
Hello,
thanks for your interest!
We're working on additional material that we can provide to enable training of the models used in this example. 
For now I can only refer you to this paper which is a good reference point for training with only small, not so important differences:   
https://doi.org/10.1109/OJSP.2023.3343320

Another manuscript related to the other two models which were trained in a similar way is currently in press. A preprint is available:	
https://doi.org/10.48550/arXiv.2405.01967

**Comment by zuowanbushiwo** [comment]
Thank you very much for your reply. I will keep an eye on this project. 
When will there be relevant codes for train? 
I tested this model and it is relatively good in terms of computational load, model size and real-time performance.
thanks！

**Comment by phuntast1c** [comment]
Thank you for your interest in this model!
I am currently working on providing a training script for the bmfwf model. I’ll let you know when the script is finished (probably later this week).

**Comment by phuntast1c** [comment]
> Thank you very much for your reply. I will keep an eye on this project. When will there be relevant codes for train? I tested this model and it is relatively good in terms of computational load, model size and real-time performance. thanks！

You can find a repository for training the model at https://github.com/phuntast1c/train_openmha_bmfwf.
Please note that a dataset containing input and target utterances with 4 input channels will be required to train the model without modification.
