### ISSUE TITLE
installing openMHA

### ISSUE THREAD

**Issue by Negar-Riazifar** [HoerTech-gGmbH/openMHA#7]
Hello,

I am a first year PhD student at the university of Warwick. I would like to use your software for my project. I was wondering whether you provide this software on virtualbox on windows operating system or not. because it would be easier to work on one operating system compared two (Linux and Windows). In other words, can I install openMHA on virtualbox on windows or it should be installed only on a seperate Linux operating system?

Kind Regards,
Negar

**Comment by tobiasherzke** [comment]
Yes it is possible.

With these drawbacks:

- The virtualization layer will slow down your audio processing.
- Additionally, the virtualized sound card in the guest will impose limits on Sound I/O.

I would not recommed this for live sound processing at all. For batch processing of sound files, it is ok.

You might also be interested that a future release (within the next 6 months) will add windows support to openMHA. However, it will still not be recommended to use windows for live sound processing.

**Comment by Negar-Riazifar** [comment]
Thank you for your propmp response. I have also another problem. I followed the instruction for installing and compiling the package on Ubuntu operating system. However, the "./configure && make" doesn't exist in my computer. The examples of configuration files also do not exist in the package. 
I was wondering whether there is a problem in installation process. I would be thankful if you could help me please.

**Comment by tobiasherzke** [comment]
Can't reproduce:
```
git clone https://github.com/HoerTech-gGmbH/openMHA.git
cd openMHA
./configure
```
works fine.
