### ISSUE TITLE
openMHA with JACK

### ISSUE THREAD

**Issue by Negar-Riazifar** [HoerTech-gGmbH/openMHA#8]
I would like to test and run the examples of the openMHA software with JACK.
According to the instruction file (section 4.2 of openMHA_application_manual.pdf) I typed ' nc localhost 33337 ' and then ' mha ?read:mha/configurations/example_dc_live.cfg '. However, the process running in the terminal takes a very long time and I have not seen anything yet which shows success or failure. when I try to close the terminal there is this alarm: 'There is still a process running in this terminal. closing the terminal will kill it.'
I would be thankful if you could help me please.

**Comment by pmaanen** [comment]
Hi Negar,
as the manual is not very clear in this section, I suspect you got the order of commands wrong. When you start mha, the executable listens to commands coming in from port 33337. Please first start openMHA and then try issuing a command with nc. Of course, if you want to try out a 'live' configuration, the JACK server has to be started before giving the 'start' command or you will get an error message.

**Comment by Negar-Riazifar** [comment]
Hello,

When I started openMHA, I got this error:
Error: (mha_parser) The keyword "" is not in the list ([nop prepare start stop release quit])
So MHA ports are not in connection window of JACK.
Could you tell me the steps in details please?

**Comment by tobiasherzke** [comment]
This section in the document has been updated in release 4.5.6.
