### ISSUE TITLE
Feature request: double buffering

### ISSUE THREAD

**Issue by m-r-s** [HoerTech-gGmbH/openMHA#9]
It would be nice to allow period lengths that are multiples of the MHA fragsize size.

**Comment by pmaanen** [comment]
Please take a look at the 'db' plugin found at mha/plugins/rate/db/db.cpp and documented in openMHA_plugins.pdf at page 55. Does this plugin suit your needs?

**Comment by m-r-s** [comment]
Yes :) This looks good!

**Comment by m-r-s** [comment]
Works nicely. The pdf documentation of the db plugin, however, refers to inexistent files.
